### ISSUE TITLE
Menyertakan Tangkapan Layar untuk Status/Komentar Terkait

### ISSUE THREAD

**Issue by freakyahh420** [zakirkun/arsip-gorengan-is#3]
Kalau berkenan, minta tolong untuk melampirkan screenshot dari status/komentar yang terlampir di file README.
Cukup status atau komentar yang dimaksud dalam pembahasan saja, tujuannya agar orang-orang tidak gagal memahami case ini karena kena limit privasi. Contohnya untuk yang berkode [FO] dan [CLOSE], yang [PUB] juga boleh buat jaga-jaga, toh repo ini judulnya ARSIP.

**Comment by SlavyanDesu** [comment]
+1

**Comment by andrinur13** [comment]
LGTM

**Comment by NikarashiHatsu** [comment]
PR added bang, makasih buat sarannya

**Comment by zakirkun** [comment]
Solve #8
